// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace StudySpace.Data.Models;

public partial class Feedback
{
    public int Id { get; set; }

    public int? UserId { get; set; }

    public int? BookingId { get; set; }

    public int? Rating { get; set; }

    public string ReviewText { get; set; }

    public DateTime? ReviewDate { get; set; }

    public virtual Booking Booking { get; set; }

    public virtual ICollection<ImageFeedback> ImageFeedbacks { get; set; } = new List<ImageFeedback>();

    public virtual Account User { get; set; }
}