// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace StudySpace.Data.Models;

public partial class ImageFeedback
{
    public int Id { get; set; }

    public int? FeedbackId { get; set; }

    public string ImageUrl { get; set; }

    public bool? Status { get; set; }

    public virtual Feedback Feedback { get; set; }
}