// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace StudySpace.Data.Models;

public partial class ImageRoom
{
    public int Id { get; set; }

    public int? RoomId { get; set; }

    public string ImageUrl { get; set; }

    public virtual Room Room { get; set; }
}