// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace StudySpace.Data.Models;

public partial class Package
{
    public int Id { get; set; }

    public string Name { get; set; }

    public decimal? Fee { get; set; }

    public string Description { get; set; }

    public double? Duration { get; set; }

    public virtual ICollection<StorePackage> StorePackages { get; set; } = new List<StorePackage>();

    public virtual ICollection<Transaction> Transactions { get; set; } = new List<Transaction>();
}