// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace StudySpace.Data.Models;

public partial class Room
{
    public int Id { get; set; }

    public string RoomName { get; set; }

    public int? StoreId { get; set; }

    public int? Capacity { get; set; }

    public decimal? PricePerHour { get; set; }

    public string Description { get; set; }

    public bool? Status { get; set; }

    public decimal? Area { get; set; }

    public virtual ICollection<Amity> Amities { get; set; } = new List<Amity>();

    public virtual ICollection<Booking> Bookings { get; set; } = new List<Booking>();

    public virtual ICollection<ImageRoom> ImageRooms { get; set; } = new List<ImageRoom>();

    public virtual Store Store { get; set; }
}