// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace StudySpace.Data.Models;

public partial class RoomAmity
{
    public int RoomId { get; set; }

    public int AmitiesId { get; set; }

    public int? Quantity { get; set; }

    public virtual Amity Amities { get; set; }

    public virtual Room Room { get; set; }
}