// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace StudySpace.Data.Models;

public partial class Space
{
    public int Id { get; set; }

    public string SpaceName { get; set; }

    public string Description { get; set; }

    public bool? Status { get; set; }

    public virtual ICollection<Room> Rooms { get; set; } = new List<Room>();
}