// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace StudySpace.Data.Models;

public partial class Store
{
    public int Id { get; set; }

    public string ThumbnailUrl { get; set; }

    public double? Longitude { get; set; }

    public double? Latitude { get; set; }

    public string Description { get; set; }

    public bool? Status { get; set; }

    public bool? IsApproved { get; set; }

    public string Name { get; set; }

    public string Email { get; set; }

    public string Password { get; set; }

    public string Address { get; set; }

    public string Phone { get; set; }

    public DateTime? CreateDate { get; set; }

    public DateTime? OpenTime { get; set; }

    public DateTime? CloseTime { get; set; }

    public bool? IsOverNight { get; set; }

    public bool? IsActive { get; set; }

    public string TaxNumber { get; set; }

    public string PostalNumber { get; set; }

    public virtual ICollection<Room> Rooms { get; set; } = new List<Room>();

    public virtual ICollection<StorePackage> StorePackages { get; set; } = new List<StorePackage>();

    public virtual ICollection<Transaction> Transactions { get; set; } = new List<Transaction>();
}