// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace StudySpace.Data.Models;

public partial class UserRole
{
    public int Id { get; set; }

    public int? UserId { get; set; }

    public string RoleName { get; set; }

    public string Description { get; set; }

    public virtual Account User { get; set; }
}